// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The courseSidebars can be generated from the filesystem, or explicitly defined here.

 Create as many courseSidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const courseSidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  courseSidebar: [{type: 'autogenerated', dirName: 'courses'}],
  // second: [{type: 'autogenerated', dirName: 'second',}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['courses/create-a-document'],
    },
  ],
   */
};

export default courseSidebars;
