name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Fetch News Daily" ]
    types:
      - completed
#  push:
#    branches:
#      - main
#    paths-ignore:
#      - README.md
#      - CODE_OF_CONDUCT.md
#      - CONTRIBUTING.md
#      - LICENSE
#      - .github/workflows/**
#      - images/**

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Web
        env:
          CHANGE_LOG: ${{ secrets.CHANGE_LOG }}
          DEPLOY_ENV: github
        run: npm run build

      - name: Update Build
        uses: actions/upload-pages-artifact@v4
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4